// source: WebKtRenderMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.WebKtHtmlElement', null, global);
goog.exportSymbol('proto.WebKtHtmlElement.Type', null, global);
goog.exportSymbol('proto.WebKtRenderMessage', null, global);
goog.exportSymbol('proto.WebKtRenderMessage.Action', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WebKtRenderMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.WebKtRenderMessage.repeatedFields_, null);
};
goog.inherits(proto.WebKtRenderMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WebKtRenderMessage.displayName = 'proto.WebKtRenderMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WebKtHtmlElement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.WebKtHtmlElement.repeatedFields_, null);
};
goog.inherits(proto.WebKtHtmlElement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WebKtHtmlElement.displayName = 'proto.WebKtHtmlElement';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.WebKtRenderMessage.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WebKtRenderMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.WebKtRenderMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WebKtRenderMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WebKtRenderMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetelementid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    action: jspb.Message.getFieldWithDefault(msg, 2, 0),
    elementList: jspb.Message.toObjectList(msg.getElementList(),
    proto.WebKtHtmlElement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WebKtRenderMessage}
 */
proto.WebKtRenderMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WebKtRenderMessage;
  return proto.WebKtRenderMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WebKtRenderMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WebKtRenderMessage}
 */
proto.WebKtRenderMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetelementid(value);
      break;
    case 2:
      var value = /** @type {!proto.WebKtRenderMessage.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 3:
      var value = new proto.WebKtHtmlElement;
      reader.readMessage(value,proto.WebKtHtmlElement.deserializeBinaryFromReader);
      msg.addElement(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WebKtRenderMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WebKtRenderMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WebKtRenderMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WebKtRenderMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetelementid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getElementList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.WebKtHtmlElement.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.WebKtRenderMessage.Action = {
  OVERWRITE: 0,
  OVERWRITE_CHILDREN: 1,
  APPEND_CHILDREN: 2
};

/**
 * optional string targetElementId = 1;
 * @return {string}
 */
proto.WebKtRenderMessage.prototype.getTargetelementid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.WebKtRenderMessage} returns this
 */
proto.WebKtRenderMessage.prototype.setTargetelementid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Action action = 2;
 * @return {!proto.WebKtRenderMessage.Action}
 */
proto.WebKtRenderMessage.prototype.getAction = function() {
  return /** @type {!proto.WebKtRenderMessage.Action} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.WebKtRenderMessage.Action} value
 * @return {!proto.WebKtRenderMessage} returns this
 */
proto.WebKtRenderMessage.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated WebKtHtmlElement element = 3;
 * @return {!Array<!proto.WebKtHtmlElement>}
 */
proto.WebKtRenderMessage.prototype.getElementList = function() {
  return /** @type{!Array<!proto.WebKtHtmlElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.WebKtHtmlElement, 3));
};


/**
 * @param {!Array<!proto.WebKtHtmlElement>} value
 * @return {!proto.WebKtRenderMessage} returns this
*/
proto.WebKtRenderMessage.prototype.setElementList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.WebKtHtmlElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.WebKtHtmlElement}
 */
proto.WebKtRenderMessage.prototype.addElement = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.WebKtHtmlElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.WebKtRenderMessage} returns this
 */
proto.WebKtRenderMessage.prototype.clearElementList = function() {
  return this.setElementList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.WebKtHtmlElement.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WebKtHtmlElement.prototype.toObject = function(opt_includeInstance) {
  return proto.WebKtHtmlElement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WebKtHtmlElement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WebKtHtmlElement.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    attributesMap: (f = msg.getAttributesMap()) ? f.toObject(includeInstance, undefined) : [],
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    childList: jspb.Message.toObjectList(msg.getChildList(),
    proto.WebKtHtmlElement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WebKtHtmlElement}
 */
proto.WebKtHtmlElement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WebKtHtmlElement;
  return proto.WebKtHtmlElement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WebKtHtmlElement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WebKtHtmlElement}
 */
proto.WebKtHtmlElement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.WebKtHtmlElement.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = msg.getAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = new proto.WebKtHtmlElement;
      reader.readMessage(value,proto.WebKtHtmlElement.deserializeBinaryFromReader);
      msg.addChild(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WebKtHtmlElement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WebKtHtmlElement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WebKtHtmlElement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WebKtHtmlElement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getChildList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.WebKtHtmlElement.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.WebKtHtmlElement.Type = {
  TEXT: 0,
  DIV: 1
};

/**
 * optional Type type = 1;
 * @return {!proto.WebKtHtmlElement.Type}
 */
proto.WebKtHtmlElement.prototype.getType = function() {
  return /** @type {!proto.WebKtHtmlElement.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.WebKtHtmlElement.Type} value
 * @return {!proto.WebKtHtmlElement} returns this
 */
proto.WebKtHtmlElement.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * map<string, string> attributes = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.WebKtHtmlElement.prototype.getAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.WebKtHtmlElement} returns this
 */
proto.WebKtHtmlElement.prototype.clearAttributesMap = function() {
  this.getAttributesMap().clear();
  return this;};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.WebKtHtmlElement.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.WebKtHtmlElement} returns this
 */
proto.WebKtHtmlElement.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated WebKtHtmlElement child = 4;
 * @return {!Array<!proto.WebKtHtmlElement>}
 */
proto.WebKtHtmlElement.prototype.getChildList = function() {
  return /** @type{!Array<!proto.WebKtHtmlElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.WebKtHtmlElement, 4));
};


/**
 * @param {!Array<!proto.WebKtHtmlElement>} value
 * @return {!proto.WebKtHtmlElement} returns this
*/
proto.WebKtHtmlElement.prototype.setChildList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.WebKtHtmlElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.WebKtHtmlElement}
 */
proto.WebKtHtmlElement.prototype.addChild = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.WebKtHtmlElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.WebKtHtmlElement} returns this
 */
proto.WebKtHtmlElement.prototype.clearChildList = function() {
  return this.setChildList([]);
};


goog.object.extend(exports, proto);
